name: Pruebas Automatizadas (CI)

# Esto define cuándo se activa el robot:
# Se activará cada vez que hagas un 'push' a la rama 'main' (o master)
on:
  push:
    branches: [ "main", "master" ]
  pull_request:
    branches: [ "main", "master" ]

jobs:
  build-and-test:

    # Computadora virtual
    runs-on: ubuntu-latest

    steps:

    # La automatización descarga el código del repositorio
    - name: Chequear código (Checkout)
      uses: actions/checkout@v4

    # La automatización instala Python 3.12
    - name: Instalar Python 3.12
      uses: actions/setup-python@v5
      with:
        python-version: "3.12"

    # 3. Se instalan las librerías del requirements.txt
    - name: Instalar dependencias
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    # 4. Se ejecutan las pruebas
    # Nota: Agregamos una variable de entorno para Matplotlib por si acaso
    - name: Ejecutar pruebas con Pytest
      env:
        MPLBACKEND: Agg  # Esto evita errores de gráficos en servidores sin pantalla
      run: |
        python -m pytest
